"""updating tables

Revision ID: e74f005f526e
Revises: f857c6db0584
Create Date: 2025-01-29 16:08:58.615902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e74f005f526e'
down_revision: Union[str, None] = 'f857c6db0584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcqs', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('mcqs', 'option1')
    op.drop_column('mcqs', 'option4')
    op.drop_column('mcqs', 'option3')
    op.drop_column('mcqs', 'option2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcqs', sa.Column('option2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mcqs', sa.Column('option3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mcqs', sa.Column('option4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mcqs', sa.Column('option1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mcqs', 'options')
    # ### end Alembic commands ###
