"""adding column

Revision ID: c82fe2b19e70
Revises: dc9b87735dd0
Create Date: 2025-01-09 18:14:17.508638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82fe2b19e70'
down_revision: Union[str, None] = 'dc9b87735dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemons', sa.Column('hhhh', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemons', 'hhhh')
    # ### end Alembic commands ###
