services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:admin1234@db:5432/pokemon_database
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: pokemon_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: